services:
  postgres:
    container_name: PetFamPostgres
    image: postgres
    restart: always
    environment:
        POSTGRES_DB: pet-fam
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    ports:
        - 5434:5432
    volumes:
    - postgres-data:/var/lib/postgresql/data

volumes:
    postgres-data: